---
version: '3.1'

services:

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Use "root" as username
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306
    # we don't need to expose this, but for dev, we want to be able to connect
    #  using a separate sql client and see the data.
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  coldfusion10:
    image: roycetech/coldfusion10_dev:0.01
    environment:
      - MYSQL_URI=db
    ports:
      - 8500:8500
    volumes:
      - ${HOME}/docker/coldfusion10/cfusion/lib/neo-datasource.xml:/opt/coldfusion10/cfusion/lib/neo-datasource.xml
      - ${HOME}/docker/coldfusion10/cfusion/lib/neo-debug.xml:/opt/coldfusion10/cfusion/lib/neo-debug.xml
      # edit and set project folder below
      - ${HOME}/projects/@rt-learn-lang/coldfusion10:/opt/coldfusion10/cfusion/wwwroot/lang_app
    depends_on:
      - db
