# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    # image: mysql:latest
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # ports:
    #   - 3306:3306

  coldfusion10:
    # image: coldfusion10_dev:0.02
    image: roycetech/coldfusion10_dev:0.01
    environment:
      - MYSQL_URI=db
    ports:
      - 8500:8500
    depends_on:
      - db
