---
version: "3.3"

services:
  backup:
    image: mazzolino/restic
    container_name: restic
    hostname: your_host_name
    environment:
      RUN_ON_STARTUP: "true" #change as you wish
      BACKUP_CRON: "0 */12 * * *" #this is twice daily, i.e., every 12 hours
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: abc123$%
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_ARGS: >-
        --tag restic-docker-backup-poc #add tags, whatever you need to mark backups
        --verbose
      RESTIC_FORGET_ARGS: >- #change as required
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: Europe/London
    volumes:
      - /Users/royce/Downloads/restic-backup:/restic #change the left hand side to where you want to store the backups.
      - /Users/royce/Downloads/tmp-for-restore:/tmp-for-restore #USE THIS FOLDER FOR RESTORE - CAN VIEW EACH CONTAINER
      - /home/ubuntu/docker:/mnt/volumes:ro
    security_opt:
      - no-new-privileges:true

  prune:
    image: mazzolino/restic
    container_name: restic-prune
    hostname: your_host_name
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "*/1 * * * * *"
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: abc123$%
      TZ: Asia/Manila
    security_opt:
      - no-new-privileges:true

  check:
    image: mazzolino/restic
    container_name: restic-check
    hostname: your_host_name
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: abc123$%
      TZ: Europe/London
    security_opt:
      - no-new-privileges:true