##################################################
# Purpose:
# Created: Wednesday, August 30, 2023 at 9:44:14 PM
##################################################

# Check the src/main/resources/layers.xml for the Maven version.
# This demo is incomplete and can proceed as an exercise perhaps another time.

build:
	mvn clean package

start:

run:
	docker run -it --rm -p 9032:8080 custom-layers-maven


manual-check:
